name: dnscrypt-proxy

on:
  push:
    branches: [ master ]
    paths:
     - '.github/workflows/dnscrypt-proxy.yml'
     - 'dnscrypt/proxy/*'
     - '!dnscrypt/proxy/*.md'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  VERSION: 2.0.35

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Login to Docker Hub Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Build Container Image
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x \
            --tag gists/dnscrypt-proxy:latest \
            --tag gists/dnscrypt-proxy:${VERSION} \
            -f ./dnscrypt/proxy/Dockerfile \
            ./dnscrypt/proxy/ \
            --push
