name: shadowsocks-libev.v2ray-plugin

on:
  push:
    branches: [ master ]
    paths:
     - '.github/workflows/shadowsocks-libev.v2ray-plugin.yml'
     - 'shadowsocks/libev\+v2ray/*'
     - '!shadowsocks/libev\+v2ray/*.md'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  VERSION: 1.3.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2
      - name: Login to Docker Hub Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Build Container Image
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x \
            --tag gists/shadowsocks-libev:v2ray-plugin-latest \
            --tag gists/shadowsocks-libev:v2ray-plugin-${VERSION} \
            -f ./shadowsocks/libev+v2ray/Dockerfile \
            ./shadowsocks/libev+v2ray/ \
            --push
